[[plugins]]
repo = 'vim-scripts/VOoM'
on_cmd = 'Voom'
[[plugins]] # 背景透過
repo = 'miyakogi/seiya.vim'
on_cmd = 'SeiyaEnable'
[[plugins]] # 置換をプレビュー
repo = 'osyo-manga/vim-over'
on_cmd = 'OverCommandLine'
[[plugins]]
repo = 'sudo.vim'
on_cmd = ['SudoWrite', 'SudoRead']
[[plugins]]
repo = 'Shougo/vimshell'
on_cmd = 'VimShell'
[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = 'GundoToggle'
[[plugins]]
repo = 'seventhsense/nerdtree'
rev  = 'development'
on_cmd = 'NERDTreeToggle'
[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_if = 1
on_cmd = 'Alignta'
# Unite source
[[plugins]]
repo = 'basyura/unite-rails'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
on_add = '''
  g:neoyank#limit
  g:neoyank#file
  g:neoyank#registers

  let g:neoyank#file = $HOME.'/.vim/yankring_history_v2.txt' 
'''
[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
[[plugins]]
repo = 'ujihisa/unite-gem'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
[[plugins]]
repo = 'pasela/unite-webcolorname'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
[[plugins]]
repo = 'seventhsense/unite-fileline'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
[[plugins]]
repo = 'Shougo/unite-outline'
on_source = 'unite.vim'
[[plugins]] # 辞書を引く
repo = 'koron/codic-vim'
[[plugins]]
repo = 'rhysd/unite-codic.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
# Unite.vim
[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
on_cmd = 'Unite'

# completion & snippets
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_event = 'InsertCharPre'
on_ft = 'snippet'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'
[[plugins]]
repo = 'honza/vim-snippets'
on_source = 'neosnippet.vim'
# html/css
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htm']
[[plugins]]
repo = 'groenewege/vim-less'
on_ft = 'less'
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'
[[plugins]]
repo = 'hail2u/vim-css-syntax'
on_ft = ['css', 'scss']
# [[plugins]]
# repo = 'vim-scripts/css_color.vim'
# on_ft = ['css', 'scss']
[[plugins]]
repo = 'Ioannis-Kapoulas/vim-autoprefixer'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'
[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = 'ruby'
on_cmd = 'Bundle'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
